### ISSUE TITLE
This is gold ! thank you for doing this, except the YAML part though.

### ISSUE THREAD

**Issue by e-nouri** [ginger-io/beyonce#19]
I made my own contraption to do the same thing same table, but multiple types, I am using graphql, so the typescript classes are part of the entire app.

Is there a technical limitation why you went with the yaml model generation ? instead of typescript decorators ?

Again thank you so much for this

**Comment by jcarver989** [comment]
Hey there,

> Is there a technical limitation why you went with the yaml model generation ? instead of typescript decorators ?

Yes and no. 

Beyonce code-generates a few things beyond just model objects (e.g. objects for your partitions, a tagged union of all your models etc) - so there's more required than just a TS interface/class per model. That being said, there's not a technical limitation as to why you couldn't define your models in TypeScript and have the code-generator use those definitions. That's significantly more involved though and requires hooking into the TS compiler to get the AST. 

Also fwiw, I'm personally not a fan of using decorators/annotations in code and thus Beyonce's design reflects those preferences. 

I think the ideal here would be to not need code-generation at all and just be able to write normal TypeScript (sans decorators). The generated code is currently fairly-short, but it's still significantly less verbose to defines things in YAML...at least as they are now. 

> Again thank you so much for this

Glad you like the project. 

One thing to be aware of is this library is  nascent and thus the current API doesn't offer the full range of DynamoDB features (it's tuned for Ginger's current use-cases). And there might be breaking API changes in the future.

**Comment by e-nouri** [comment]
I see your point, I actually ended up running the codegen couple of times after that i had an idea on how to write the models myself.

I can see the use for the YAML though, I used to do the same, because I needed `types` for both javascript and python, and YAML was handy and less cluttered.

Here is the type of classes I am using to make the models,  generate the graphql schema and so on:

```
@ObjectType({ description: "User device for mobile, tablette or web" })
export class Device {
    model: ModelType.Device

    @Field(type => ID)
    id: string;

    @Field()
    userId: string;

    @Field()
    token: string;

    @Field()
    platform: string;

    @Field()
    active:boolean;

    @Field()
    uuid: string

    @Field(type => Int)
    createdAt: number;
}
```

Much appreciate your effort guys open sourcing this, I'll be more than happy to help out, and make PRs when needed.

**Comment by jcarver989** [comment]
PRs would certainly welcome and appreciated!

In particular, Beyonce currently doesn't support the full range of DynamoDB operations (e.g. missing update, delete...), comparison operators (e.g. begins_with, contains, size...), and expressions (e.g. conditional expressions). So those would be great areas for improvement. 

Re: graphQL schema generation from the Dynamo model definitions, it's certainly a valid use-case, although it's out of scope for Beyonce. It'd make a great add-on / supporting library though. The main reason why I say this is that database libraries imo shouldn't make assumptions about the structure of your API.
