### ISSUE TITLE
Put and ReturnValue

### ISSUE THREAD

**Issue by e-nouri** [ginger-io/beyonce#25]
I think it would be very useful to add an argument to get the return value on inserted records with the default behaviour no return.

**Comment by jcarver989** [comment]
Not clear on what you're asking for here - did you want the API to echo back the inserted item or are you trying to retrieve something like consumed capacity?

**Comment by e-nouri** [comment]
The inserted Item as an option parameter to return it or not.

**Comment by jcarver989** [comment]
Could you give a bit more context about your use-case? It seems like you'd already have the item you want to insert in memory because you'd have to call `beyonce.put(item)` anyways -- right?

**Comment by e-nouri** [comment]
This is more related to the update more than the insert, in my case I update the record and then I put a message in a queue to do more things like notifications and such, having the returned value as an option will allow me to put that value in the message straight away, not doing another read, having that options can help in such case.

**Comment by jcarver989** [comment]
Partial updates that return the full DynamoDB object, should now be supported as of 0.0.37. Docs here: https://github.com/ginger-io/beyonce#update

Feel free to re-open this issue if this doesn't cover what you had in mind.
