### ISSUE TITLE
Using Beyonce with Dataloader

### ISSUE THREAD

**Issue by e-nouri** [ginger-io/beyonce#31]
I am using dataloader and I want to keep the type checking which Dataloader does support, that's why I find it it useful to export the keys types.

Also the returned value of the batchGet function is like so:

```
    batchGet<T extends PartitionAndSortKey<TaggedModel>>(params: {
        keys: T[];
        consistentRead?: boolean;
    }): Promise<GroupedModels<ExtractKeyType<T>>>;
```

Dataloader expects an array of Promises which makes it incompatible:
`DataLoader must be constructed with a function which accepts Array<key> and returns Promise<Array<value>>`

**Comment by e-nouri** [comment]
I came up with this in the meanwhile:


```
import DataLoader = require('dataloader');
import { Model } from "../models";

export declare type TaggedModel = Record<string, any> & {
    model: string;
};

export declare class PartitionAndSortKey<T extends TaggedModel> {
    readonly partitionKeyName: string;
    readonly partitionKey: string;
    readonly sortKeyName: string;
    readonly sortKey: string;
    readonly modelTag: T["model"];
    constructor(partitionKeyName: string, partitionKey: string, sortKeyName: string, sortKey: string, modelTag: T["model"]);
}


export class Loader extends DataLoader<PartitionAndSortKey<Model>, Model, String>{}

```

```
const dataLoader = new Loader(async (keys) =>{
    let retval: Model[] = [];
    // @ts-ignore:
    const results = await db.batchGet({keys})
    for (let k of keys){
        if (results[k.modelTag]){
            for (let m of results[k.modelTag]){
                retval.push(m)
            }
        }
    }
    return retval
}, {
    cache: true,
    cacheKeyFn: (key)=>`${key.partitionKey}:${key.sortKey}`
});
```

**Comment by jcarver989** [comment]
Exporting the various xxxKey types sounds reasonable. 

Per DataLoader, assuming your data loaders are setup per partition, or per model, I'm not following why you can't just map Beyonce's result to the type that your data loader wants? 

The `GroupedModels<...>` type just groups each model type into its own array. So you can either extract the specific model type(s) (if you know them) or simply walk the object and merge the arrays together. 

I don't think the return type of Beyonce's `batchGet` should be a single array as it can return heterogenous model types. And it's generally nicer for the caller to have them grouped by type vs mixed together into a single array.

**Comment by e-nouri** [comment]
A Dataloader per model will not save me much, because of the hashmap get(model), but the array is the problem, because dataloader takes an array of keys, and bachtget expects a set of keys (uniq). that will result in incorrect order of the promises returned by the dataloader or the number not muching. Does that make sense ?

To give you some context, I am running a custom Graphql deployment on Lambda with Dynamodb and SQS, etc.

**Comment by jcarver989** [comment]
>  but the array is the problem, because dataloader takes an array of keys, and bachtget expects a set of keys (uniq). that will result in incorrect order of the promises returned by the dataloader or the number not muching. Does that make sense ?

Sure. I understand that data-loader expects you to return an array of results that's ordered to match the input array. And that DataLoader sends an array that may or may not contain duplicate ids. 

But keep in mind that DynamoDB itself does not order its results (from the docs): 

 > When designing your application, keep in mind that DynamoDB does not return items in any particular order

So I don't view "re-order my keys b/c DataLoader wants them this way" as  within the scope of Beyonce "core". That being said, I do see the value in having guidance in the docs on how to use Beyonce with DataLoader, which basically boils down into a mapping function from array => set => beyonce => sort the return keys.

This functionality could always be offered as an "add-on" to Beyonce "core", e.g. could be made available via a beyonce-dataloader or similarly named package.

**Comment by e-nouri** [comment]
Yes that makes sense, thank you for point out the order, I red the doc but I forget to add the reorder in the end, something like this can do the trick:

```
async function batchGet(keys: PartitionAndSortKey<Model>[]){
    let uniqKeys: Map<String, PartitionAndSortKey<Model>> = new Map();
    let uniqResults: Map<String, Model> = new Map();

    for (let k of keys){
        let hash = getHash(k);
        if(!uniqKeys.has(hash)){
            uniqKeys.set(hash, k)
        }
    }

    let uniqKeysList = Array.from(uniqKeys.values());

    // @ts-ignore:
    const results = await db.batchGet({keys: uniqKeysList})
    for (let k of uniqKeysList){
        if (results[k.modelTag]){
            for (let m of (results[k.modelTag] as Model[])){
                uniqResults.set(getHash(k), m)
            }
        }
    }

    // Reorder results
    return keys.map((k)=>{
        let hash = getHash(k);
        if (uniqResults.has(hash)){
            return uniqResults.get(hash) as Model
        }else{
            return new Error(`Key ${hash} has no result`, );
        }
    })
}
```
